version: '3'
services:
  eclipse:
    image: xavierdpt/eclipse
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ./sample_projects:/home/user/projects
    depends_on:
      - tomcat
  tomcat: 
    image: xavierdpt/tomcat
    volumes:
      - ./tomcat-users.xml:/opt/apache-tomcat-9.0.14/conf/tomcat-users.xml
      - ./manager-context.xml:/opt/apache-tomcat-9.0.14/webapps/manager/META-INF/context.xml
    ports:
      - "8080:8080"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbit"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
