# https://docs.vagrantup.com.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
   end
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update 
    apt-get upgrade -y
    apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce
    usermod -aG docker vagrant
  SHELL

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.26"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-master"
    end
    master.vm.provision "shell", inline: <<-SHELL
      docker swarm init --advertise-addr 192.168.33.26 | grep "docker swarm join --token" >> /vagrant_data/join_swarm.sh
      docker service create --name nginx -p 8080:80 --replicas 3 nginx
    SHELL
  end

  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.box = "ubuntu/trusty64"
    worker.vm.network "private_network", ip: "192.168.33.28"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-worker1"
    end
    worker.vm.provision "shell", inline: <<-SHELL
      sh /vagrant_data/join_swarm.sh
    SHELL
  end

  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.box = "ubuntu/trusty64"
    worker.vm.network "private_network", ip: "192.168.33.27"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-worker2"
    end
    worker.vm.provision "shell", inline: <<-SHELL
      sh /vagrant_data/join_swarm.sh
    SHELL
  end
end
